### ISSUE TITLE
Cannot read property Error

### ISSUE THREAD

**Issue by lopemac** [digistump/OakCLI#18]
With the OakCLI 1.0.0 I get this
Logging in to Particle...
No devices available.
Press enter to exit.
With OakCLI 1.0.2 I get this
Logging in to Particle...
nexe.js:43520
      if(err.code !== undefined){
            ^
TypeError: Cannot read property 'code' of null
    at nexe.js:43520:13
    at Spark.emitAndCallback (nexe.js:31377:42)
    at null.<anonymous> (nexe.js:31505:10)
    at Request.self.callback (nexe.js:28860:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (nexe.js:29697:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (nexe.js:29624:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

I really want to use my oaks. Why am I getting these errors? I'm on OSX 10.11.4 and my oak has a local IP address.

**Comment by thunderace** [comment]
For the first one (No devices available.) please see [http://digistump.com/wiki/oak/tutorials/connecting](url).
For the second one, it's a bug, i make a pull request to fix it.
